substitutions:
  fw_version: "0.9.0"

esphome:
  name: a6v3
  friendly_name: a6v3
  includes:
    - webui.h        # Enthält dein eigenes HTML-UI
  project:
    name: "kc868.a6-heizung"
    version: "${fw_version}"
  # Build-Optionen (optional, können gelöscht werden wenn störend)
  platformio_options:
    lib_deps:
      - adafruit/Adafruit BusIO @ ^1.14.5
    lib_ldf_mode: deep+
    build_flags:
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Wire/src
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

preferences:
  flash_write_interval: 10min
  
# WLAN
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none
  ap:
  
# Lokaler Webserver (Port 80)
web_server:
  port: 80
  auth:
    username: admin
    password: heizung123

# Logger (Debug für Tests)
logger:
  level: DEBUG

# Home Assistant / API Verbindung
api:
  password: ""
  services:
    - service: set_zieltemperatur
      variables:
        temp: float
      then:
        - lambda: |-
            id(zieltemperatur) = temp;
            id(pid_integral) = 0.0;
            id(pid_last_error) = 0.0;
            ESP_LOGI("PID", "Zieltemperatur gesetzt: %.2f, Integral und Last Error zurückgesetzt.", temp);

# OTA Updates
ota:
  platform: esphome
  password: !secret ota_password

# Fallback-Portal (bei WLAN-Verbindungsfehler)
captive_portal:

# Integriere bestehende Logik aus den Paketdateien
packages:
  heizung: !include heizung.yaml
  pool: !include pool.yaml